model: us.anthropic.claude-opus-4-20250514-v1:0
api: bedrock
max_tokens: 32000
concurrent_requests: 4
temperature: 1
top_p: null
thinking:
  type: enabled 
  budget_tokens: 31000
read_cost: 15
write_cost: 75
batch_processing: true
human_readable_id: Claude 4 Opus (Thinking)
date: "2025-05-22"