competition: mmmu_finance
dataset_path: MMMU/MMMU
dataset_config: Finance
dataset_split: validation
date: "2024-01-01"
instruction: "You are given a question from the MMMU (Multi-discipline Multimodal Understanding) benchmark in the field of Finance.\n
    \ Reason step by step, and put your final answer within \\boxed{{}}.\n
    \ If the question is multiple choice with options (A, B, C, D, etc.), refer to the given options and put only the letter in \\boxed{{}}.\n
    \ An example of a valid multiple choice answer is \\boxed{{A}}. Do not put your answer text in boxed for multiple choice questions;\n
    \ for example \\boxed{{42}} is not a valid answer; instead find that value in the options list and report the corresponding letter.\n
    \ If the question is open-ended, answer using a single word or phrase within \\boxed{{}}.\n"
n_problems: 30
strict_parsing: false
final_answer: true
is_mmmu: true