model: qwen/qwen3-235b-a22b-thinking-2507
api: together
max_tokens: 81920
temperature: 0.6
top_p: 0.95
top_k: 20
provider:
  allow_fallbacks: False
  order:
  - Together
concurrent_requests: 16
read_cost: 0.6
write_cost: 1.2
human_readable_id: Qwen3-235B-2507-Think
date: "2025-07-25"
