model: google/gemini-2.5-pro
api: openrouter
max_tokens: null
temperature: 0.6 # Initally null
top_p: null
concurrent_requests: 8
max_tokens: 130000
read_cost: 1.25
tool_choice: auto
write_cost: 10.00
human_readable_id: Gemini 2.5 Pro
date: "2025-06-17"
extra_body:
  extra_body:
    google:
      thinking_config:
        include_thoughts: true
